import './globals.css'
import Navbar from '@root/components/Navbar'

export const metadata = {
  title: 'Txabi\'s Artfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  )
}
